#Application Configuration
server:
  port: 8093
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:8092/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
      path: /console
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/customerservice?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      username: root
      password:

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8097/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"